### ISSUE TITLE
Using Fuse 6.3.0 on production

### ISSUE THREAD

**Issue by MariuszHxGNMIN** [jboss-fuse/fuse#387]
Hi All
I'm trying to understand the licensing of fuse 6.3.0. If I will clone it from this Git repo and build it by myself can I use it and redistribute it to production according to Apache 2.0 License or do I need Red Had Subscription for this ? to be honest with you all this is very unclear

**Comment by zregvart** [comment]
Hi @MariuszHxGNMIN all the code you see in this repository is licensed according to the [Apache 2.0 License](https://github.com/jboss-fuse/fuse/blob/6.3.0.redhat/license.txt). Red Hat provides support and services around this when it's productised and to receive support and services you need a [subscription](https://www.redhat.com/en/about/value-of-subscription). You can read more on the [Fuse landing page on Red Hat portal](https://www.redhat.com/en/technologies/jboss-middleware/fuse).

**Comment by MariuszHxGNMIN** [comment]
@zregvart Ok.. that is clear.. but I still don't understand does it mean that if I will take a code and use it on production (according to Apache 2.0 I could do that) I will have to pay for a subscription or not? If I don't need a support what then?

**Comment by zregvart** [comment]
@MariuszHxGNMIN please consult the pages I linked above for details. You don't have to pay anything for using the software, only if you wish to pay for the support.
