### ISSUE TITLE
How to write a connector?

### ISSUE THREAD

**Issue by stephanrauh** [jboss-fuse/fuse#416]
I'd like to use the JBoss Fuse ESB. The major part of our application connects to Fuse via Webservices (i.e. SOAP). However, we have a few devices speaking a different protocol (Modbus/TCP). I haven't found a third-party adapter. So I'd like to write it myself.

Where can I find the documentation about writing connectors? Is there an example source code?

Thanks in advance
Stephan

**Comment by apupier** [comment]
Hello,

a ControlBus component is available in Camel:
http://camel.apache.org/controlbus.html

Someone developed Jamod components:
https://github.com/sworisbreathing/camel-jamod

If you want to write your own camel connector, please have a look to Camel documentation: http://camel.apache.org/writing-components.html

You can also have a look to Forge command:
- install fuse-forge addon if not yet available:
![image](https://user-images.githubusercontent.com/1105127/29015396-29017436-7b4e-11e7-8eb3-be9e55882188.png)
1. Use 'command-list' in forge console to ensure you see api-component-* commands for working with an API Component project
2. Use 'project-new' to create an empty project to start
3. Use 'api-component-setup' to add camel config and starting point code
4. Use 'api-component-add-api' to add an API to the project
5. Use the rest of the 'api-component-*' commands to add other bits needed in the API component project

Regards,

**Comment by stephanrauh** [comment]
Thanks!
